### ISSUE TITLE
Final Project Week One - Adi

### ISSUE THREAD

**Issue by Adi-K-Coding** [Archkitten/n22p4-quarter-finals#6]
- [x] Roster for girls and boys team
- [ ] Rankings API
- [ ] Working on Crud login redirect
- [ ] navbar - login and logout button

**Comment by Archkitten** [comment]
Worked on logins and user database, the baseline for our entire website. Spent a lot of time fixing issues and making the search bar work with the api, is currently thinking about a way to search for more than just a name without using a new search bar.
