### ISSUE TITLE
Final Project Week One - Samaya

### ISSUE THREAD

**Issue by samayass** [Archkitten/n22p4-quarter-finals#7]
- [x] [Commit for photo gallery with local storage](https://github.com/Archkitten/n22p4-quarter-finals/commit/18059c2df743d0f035fcb14ab34215c2410bedeb)
- [x] [ Commit for search bar for roster pages](https://github.com/Archkitten/n22p4-quarter-finals/commit/53d0b6ff8eff4d7e1cf67167b3f64cc1e267a5c1)
- [ ] Working on displaying login logout for navbar depending on if user is logged in or not
- [x] [Commit for workouts page which is a quiz to display what workout user should do based on input](https://github.com/Archkitten/n22p4-quarter-finals/commit/cae73a79478b883f9d6fec972b4c699138373b59)
[- [ ] Calendar with local storage](https://github.com/Archkitten/n22p4-quarter-finals/commit/93fb4fdd12006e10c76de09e61c80f73b83ebc69)

**Comment by Adi-K-Coding** [comment]
gj
